Layout trainees
bistecglobal/blockchain-certificates-issuer pull request #139
Opened 2023-08-07 08:39 UTC by chalana1995

2023-08-08 05:38 UTC, chan4lk requested changes
fix mentioned issues

2023-08-08 05:38 UTC, chan4lk commented on src/portals/blockchain-frontend/apps/blockchain-frontend/components/trainees-container/state.tsx
> +    console.log("=====ds",dataSource);
remove log

2023-08-08 12:58 UTC, chamal817 approved these changes

2023-08-08 13:01 UTC, chalana1995 commented on src/portals/blockchain-frontend/apps/blockchain-frontend/components/trainees-container/state.tsx
> +    console.log("=====ds",dataSource);
confict fixed

2023-08-09 05:48 UTC, chan4lk approved these changes

2023-08-09 05:48 UTC, merged