Features/create trainee
bistecglobal/blockchain-certificates-issuer pull request #39
Opened 2023-05-19 06:59 UTC by chamal817

2023-05-20 23:41 UTC, gayashan4lk requested changes

2023-05-20 23:41 UTC, gayashan4lk commented on src/portals/blockchain-frontend/apps/blockchain-frontend/components/trainers-container/TrainenersContainer.tsx
Fix typo in file name.
`TrainersContainer`

2023-05-22 06:33 UTC, chamal817 commented on src/portals/blockchain-frontend/apps/blockchain-frontend/components/trainers-container/TrainenersContainer.tsx
fixed

2023-05-23 04:57 UTC, gayashan4lk approved these changes

2023-05-23 04:58 UTC, merged